### PR TITLE
Fix tests again

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes the test suite to account for changes upstream.

### CODE REVIEW

**Review by martinberoiz — APPROVED** [review]
looks good to me

**Comment by duncanmmacleod** [comment]
@martinberoiz, was there a way for me to know ahead of time that the `tenyear` dataset would disappear? Was this announced?

**Comment by martinberoiz** [comment]
Let me check why it's not showing. To be honest, I didn't know it was not showing.

**Comment by martinberoiz** [comment]
Hi Duncan, the `tenyear` dataset was replaced by `history`, there was no announcement for this.

https://www.gw-openscience.org/timeline/show/history/

I'm working now on writing documentation for the current public API and tidying things up a bit, hopefully changes like this will not happen without sending warnings in the future. I want to make API tighter in this sense but it will take me some time.

I thought of adding an extra `warning` key to the json with deprecation warnings, an `error` key explaining errors, etc. Do you think this would be a good idea? How would you prefer be notified? I'm thinking of making it fair for anyone having a "client" and not just this one in particular.

**Comment by duncanmmacleod** [comment]
@martinberoiz, since human's don't really parse the JSON, I don't think `warnings` would help here. However, just keeping this project in the loop of upstream changes via tickets here would be great. Thanks.

**Comment by martinberoiz** [comment]
Well, I was thinking that the gwosc client could just echo the warnings and errors back to the user. So if there's any deprecation coming the user will have time to upgrade gwosc client without breaking code?

That wouldn't help you the developer though, so we will let you know opening issues here.

**Pull request merged**
