### PR TITLE
Editing window of data being fetched

### PR DESCRIPTION
**Pull request by virginiademi**
Increasing time window by 4000s before and after the event time in order to fetch the data events given a trigger time in bilby.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@virginiademi, thanks for this, can you add a comment in the code to explain _why_ (a) we have a padding at all, annd (b) why this particular padding?

**Comment by virginiademi** [comment]
Yes, will do!

**Comment by duncanmmacleod** [comment]
So the failing tests are probably not your fault, you will need to rebase after #25 is merged, but can you add a unit test to check that with this change in place we can query for URLs in event datasets when the GPS interval doesn't overlap with the GPS time of the event?

**Comment by virginiademi** [comment]
OK, I'll add a function to the test_locate.py script to see if I can fetch data the way bilby attempts to.

**Comment by duncanmmacleod** [comment]
Superseded by #29.

**Pull request closed without merging**
